apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-kubia
spec:
  replicas: 3
  selector:
    app: l-rc-kubia
  template:
    metadata:
      name: rc-pod-kubia
      labels:
        app: l-rc-kubia
    spec:
      containers:
      - image: dlnreddy/kubia
        name: kubia
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 1  
