apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-v1
spec:
  replicas: 3
  template:
    metadata:
      name: pod-kubia
      labels:
        app: kubia
    spec:
      containers:
      - name: container-kubia
        image: dlnreddy/kubia:v1

---

apiVersion: v1
kind: Service
metadata:
  name: svc-kubia
spec:
  type: LoadBalancer
  selector: 
    app: kubia
  ports:
  - port: 80
    targetPort: 8080

